environment: dev

# Rest API
rest_host: pos-integration-deposit-solutions.apps.openshift.musala.com
rest_username: posintegration
rest_password: posintegration

# Database PostgreSQL
db_url: jdbc:postgresql://db-pos-integration-ext-deposit-solutions.apps.openshift.musala.com:32253/db-pos-integration
db_username: testuser
db_password: testpass

# Mailhog API
mail_host: mailhog-pos-integration-http-deposit-solutions.apps.openshift.musala.com
mail_username: deposit_user
mail_password: deposit_pass